import 'package:flutter/material.dart';

const Color yellowColor = Color(0xffFFC700);
const Color liteBlackColor = Color(0xff474747);
const Color darkLiteColor = Color(0xff373636);
const Color blackColor = Color(0xff2F2E36);
const Color darkColor = Color(0xff535252);
const Color greyColor = Color(0xff7B7B7B);
const Color liteWhiteColor = Color(0xffD9D9D9);
const Color liteWhite2Color = Color(0xffF5F5F5);
const Color white4Color = Color(0xffEFF9F6);
const Color white3Color = Color(0xffE7EFFF);
const Color veryGreyColor = Color(0xffDDDDDD);
const Color liteGreyColor = Color(0xff999999);
const Color whiteColor = Color(0xffFFFFFF);
const Color blueColor = Color(0xff0062FF);
const Color tealLiteColor = Color(0xff109C9C);
const Color tealColor = Color(0xff3DD598);
const Color greenColor = Color(0xff4CAF50);
const Color fullGreenColor = Color(0xff13C11A);
const Color fulRedColor = Color(0xffC82727);
const Color liteRedColor = Color(0xffFF2727);
const Color red1Color = Color(0xffD91717);
const Color redWhiteColor = Color(0xffFCF2F2);
const Color dallBlackColor = Color(0xff5A5A5A);
const Color whiteBackGround = Color(0xffF2F6FF);
const Color redColor = Color(0xffC82727);
const Color lightBlueColor = Color(0xff8DA6FF);
